# Wrapper sensor for sensor sr_waste_yellow of waste_collection_schedule
sensor:
  - name: sr_waste_yellow_ex
    unique_id: sr_waste_yellow_ex
    picture: /local/img/yellow.png
    icon: mdi:recycle
    #unit_of_measurement: Tage
    state: > 
        {% from 'get_waste_state.jinja' import get_waste_state %}        
        {{get_waste_state('yellow')}}  
    attributes:
      full: >
        {{ states('sensor.sr_waste_yellow') }}      
      date: > 
        {% from 'get_waste_date.jinja' import get_waste_date %}        
        {{get_waste_date('yellow')}}  
      day: > 
        {% from 'get_waste_day.jinja' import get_waste_day %}        
        {{get_waste_day('yellow')}}       
      formatted: > 
        {% from 'get_waste_days_to_formatted.jinja' import get_waste_days_to_formatted %}        
        {{get_waste_days_to_formatted('yellow')}}  
#        , {{ date }}