# Wrapper sensor for sensor sr_waste_blue of waste_collection_schedule
sensor:
  - name: sr_waste_blue_ex
    unique_id: sr_waste_blue_ex
    picture: /local/img/blue.png
    icon: mdi:file
    #unit_of_measurement: Tage
    state: > 
        {% from 'get_waste_state.jinja' import get_waste_state %}        
        {{get_waste_state('blue')}}  
    attributes:
      full: >
        {{ states('sensor.sr_waste_blue') }}      
      date: > 
        {% from 'get_waste_date.jinja' import get_waste_date %}        
        {{get_waste_date('blue')}}  
      day: > 
        {% from 'get_waste_day.jinja' import get_waste_day %}        
        {{get_waste_day('blue')}}        
      formatted: > 
        {% from 'get_waste_days_to_formatted.jinja' import get_waste_days_to_formatted %}        
        {{get_waste_days_to_formatted('blue')}}  
#        , {{ date }}
