# Wrapper sensor for sensor sr_waste_grey of waste_collection_schedule
sensor:
  - name: sr_waste_grey_ex    
    unique_id: sr_waste_grey_ex    
    picture: /local/img/grey.png
    icon: mdi:trash-can
    #unit_of_measurement: Tage
    state: > 
        {% from 'get_waste_state.jinja' import get_waste_state %}        
        {{get_waste_state('grey')}}  
    attributes:
      full: >
        {{ states('sensor.sr_waste_grey') }}      
      date: > 
        {% from 'get_waste_date.jinja' import get_waste_date %}        
        {{get_waste_date('grey')}}  
      day: > 
        {% from 'get_waste_day.jinja' import get_waste_day %}        
        {{get_waste_day('grey')}}  
      formatted: > 
        {% from 'get_waste_days_to_formatted.jinja' import get_waste_days_to_formatted %}        
        {{get_waste_days_to_formatted('grey')}}  
#        , {{ date }}
