# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named integrations
  allowlist_external_dirs:
    - "/config"
    - "/share/backup"
    - "/share/homeassistant_samba_backup"