sensor:
  - name: sr_energy_info_dish_fridge
    unique_id: sr_energy_info_fridge
    icon: mdi:currency-eur
    state: >
        {% set myString = "" %}
        {{ myString }}
    attributes:
      daily_ex: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ku_steckdose_kuhlschrank_daily', true)}}         
      weekly_ex: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ku_steckdose_kuhlschrank_weekly', true)}}         
      monthly_ex: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ku_steckdose_kuhlschrank_monthly', true)}}         
      yearly_ex: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ku_steckdose_kuhlschrank_yearly', true)}}         
      daily: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ku_steckdose_kuhlschrank_daily', false)}}         
      weekly: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ku_steckdose_kuhlschrank_weekly', false)}}         
      monthly: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ku_steckdose_kuhlschrank_monthly', false)}}         
      yearly: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ku_steckdose_kuhlschrank_yearly', false)}}      
