sensor:

  - name: sr_extern_backup_number_of_files
    unique_id: sr_extern_backup_number_of_files
    state: >
      {% if not state_attr('sensor.homeassistant_samba_backup','number_of_files') is none %}      
        {{state_attr('sensor.homeassistant_samba_backup','number_of_files')}}
      {% endif %}        

  - name: sr_extern_backup_last_changed
    unique_id: sr_extern_backup_last_changed    
    state: >
      {% if has_value('sensor.homeassistant_samba_backup') %}  
        {% if states.sensor.homeassistant_samba_backup.last_changed %}                  
          {{ as_timestamp(states.sensor.homeassistant_samba_backup.last_changed) |
          timestamp_custom('%d.%m.%Y %H:%M') }}
        {% endif %}    
      {% endif %}  

  - name: sr_extern_backup_size
    unique_id: sr_extern_backup_size
    unit_of_measurement: GB
    device_class: data_size
    state: >
      {% if has_value('sensor.homeassistant_samba_backup') %}      
        {{states('sensor.homeassistant_samba_backup')}}
      {% endif %}    

  - name: sr_extern_calc_average_backup_file_size
    unique_id: sr_extern_calc_average_backup_file_size
    unit_of_measurement: MB
    device_class: data_size
    state: >
      {% if has_value('sensor.homeassistant_samba_backup') and state_attr('sensor.homeassistant_samba_backup', 'number_of_files') != none %}
        {{ (float(states('sensor.homeassistant_samba_backup')) / float(state_attr('sensor.homeassistant_samba_backup', 'number_of_files'))) | round(2)}}
      {%endif%}