sensor:
  - name: sr_energy_info_3d_printer
    unique_id: sr_energy_info_3d_printer
    icon: mdi:currency-eur
    state: >
        {% set myString = "" %}
        {{ myString }}
    attributes:
      daily_ex: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_dg_steckdose_3d_drucker_daily', true)}}         
      weekly_ex: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_dg_steckdose_3d_drucker_weekly', true)}}         
      monthly_ex: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_dg_steckdose_3d_drucker_monthly', true)}}         
      yearly_ex: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_dg_steckdose_3d_drucker_yearly', true)}}         
      daily: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_dg_steckdose_3d_drucker_daily', false)}}         
      weekly: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_dg_steckdose_3d_drucker_weekly', false)}}         
      monthly: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_dg_steckdose_3d_drucker_monthly', false)}}         
      yearly: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_dg_steckdose_3d_drucker_yearly', false)}}   
