sensor:
  - name: sr_energy_info_washing_machine
    unique_id: sr_energy_info_washing_machine
    icon: mdi:currency-eur
    state: >
        {% set myString = "" %}
        {{ myString }}
    attributes:
      daily_ex: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ke_steckdose_waschmaschine_daily', true)}}            
      weekly_ex: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ke_steckdose_waschmaschine_weekly', true)}}            
      monthly_ex: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ke_steckdose_waschmaschine_monthly', true)}}            
      yearly_ex: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ke_steckdose_waschmaschine_yearly', true)}}            
      daily: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ke_steckdose_waschmaschine_daily', false)}}            
      weekly: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ke_steckdose_waschmaschine_weekly', false)}}            
      monthly: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ke_steckdose_waschmaschine_monthly', false)}}            
      yearly: >
        {% from 'get_energy_costs_for.jinja' import get_energy_costs_for %}        
        {{get_energy_costs_for('um_ke_steckdose_waschmaschine_yearly', false)}}       
