sensor:

  - name: sr_local_backup_number_of_files
    unique_id: sr_local_backup_number_of_files
    state: >
      {% if not state_attr('sensor.backup','number_of_files') is none %}      
        {{state_attr('sensor.backup','number_of_files')}}
      {% endif %}        

  - name: sr_local_backup_last_changed
    unique_id: sr_local_backup_last_changed
    state: >
      {% if has_value('sensor.backup') %}      
        {% if states.sensor.backup.last_changed %}                  
          {{ as_timestamp(states.sensor.backup.last_changed) |
          timestamp_custom('%d.%m.%Y %H:%M') }}
        {% endif %}              
      {% endif %}

  - name: sr_local_backup_size
    unique_id: sr_local_backup_size
    unit_of_measurement: GB
    device_class: data_size
    state: >
      {% if has_value('sensor.backup') %}      
        {{states('sensor.backup')}}
      {% endif %}    

  - name: sr_local_calc_average_backup_file_size
    unique_id: sr_local_calc_average_backup_file_size
    unit_of_measurement: MB
    device_class: data_size
    state: >
      {% if has_value('sensor.backup') and state_attr('sensor.backup', 'number_of_files') != none and float(state_attr('sensor.backup', 'number_of_files')) > 0 %}
        {{ (float(states('sensor.backup')) / float(state_attr('sensor.backup', 'number_of_files'))) | round(2)}}
      {%endif%}      