sensor:
  - unique_id: sr_local_nuc_disk_use
    name: sr_local_nuc_disk_use
    unit_of_measurement: "GB"
    device_class: data_size 
    state_class: measurement
    state: "{{ (states('sensor.disk_use') | float) | round(2) }}"