sensor:
  - name: sr_count_entities
    state: "{{ states | length }}"

  - name: sr_count_switch  
    state: "{{ states.switch | list | count }}"

  - name: sr_count_alerts  
    state: "{{ states.alert | list | count }}"

  - name: sr_count_automations  
    state: "{{ states.automation | list | count }}"  

  - name: sr_count_binary_sensors  
    state: "{{ states.binary_sensor | list | count }}"    

  - name: sr_count_cameras  
    state: "{{ states.camera | list | count }}" 

  - name: sr_count_climates  
    state: "{{ states.climate | list | count }}"     

  - name: sr_count_counters  
    state: "{{ states.counter | list | count }}" 

  - name: sr_count_devices  
    state: "{{ states.device_tracker | list | count }}" 

  - name: sr_count_groups  
    state: "{{ states.group | list | count }}" 

  - name: sr_count_image_processing  
    state: "{{ states.image_processing | list | count }}"     

  - name: sr_count_boolean  
    state: "{{ states.input_boolean | list | count }}"         

  - name: sr_count_datetime  
    state: "{{ states.input_datetime | list | count }}"   

  - name: sr_count_number  
    state: "{{ states.input_number | list | count }}"     
  
  - name: sr_count_select  
    state: "{{ states.input_select | list | count }}"  

  - name: sr_count_text  
    state: "{{ states.input_text | list | count }}"

  - name: sr_count_lights  
    state: "{{ states.light | list | count }}"           
  
  - name: sr_count_locks  
    state: "{{ states.lock | list | count }}"     
  
  - name: sr_count_media_player  
    state: "{{ states.media_player | list | count }}"  

  - name: sr_count_person  
    state: "{{ states.person | list | count }}"  

  - name: sr_count_plants  
    state: "{{ states.plant | list | count }}"      

  - name: sr_count_rest  
    state: "{{ states.rest_command | list | count }}"  

  - name: sr_count_script  
    state: "{{ states.script | list | count }}"     

  - name: sr_count_sensors  
    state: "{{ states.sensor | list | count }}"       

  - name: sr_count_timer  
    state: "{{ states.timer | list | count }}" 

  - name: sr_count_utility_meter  
    state: "{{ states.utility_meter | list | count }}"     
  
  - name: sr_count_vacuum  
    state: "{{ states.vacuum | list | count }}"

  - name: sr_count_weather  
    state: "{{ states.weather | list | count }}"    