sensor:

  - name: sr_fl_nuki_frontdoor_security_state_icon
    unique_id: sr_fl_nuki_frontdoor_security_state_icon
    state: >
      {% set security_states = states('sensor.nuki_haustur_door_security_state') %}
      {% if security_states == 'Closed & Unlocked' %}
        mdi:door-closed
      {% elif security_states == 'Closed & Locked' %}  
        mdi:door-closed-lock
      {% else %} 
        mdi:door-open
      {% endif %}

  - name: sr_fl_nuki_frontdoor_security_state
    unique_id: sr_fl_nuki_frontdoor_security_state
    state: >
      {% set security = states('sensor.nuki_haustur_door_security_state') %}
      {% set security_states = {
        "Closed & Unlocked": "Geschlossen und Entriegelt",
        "Closed & Locked": "Geschlossen und Verriegelt",
        "Open": "Geöffnet",  
        "unavailable": "Nicht verfügbar"}
      %}
      {{security_states[security]}}
    icon: "{{states('sensor.sr_fl_nuki_frontdoor_security_state_icon')}}"

  - name: sr_fl_nuki_frontdoor_info_security_state
    unique_id: sr_fl_nuki_frontdoor_info_security_state
    state: >
      {% set security_state = states('sensor.nuki_haustur_door_security_state') %}
      {% if security_state == 'Closed & Unlocked' %}
        Die Haustür ist geschlossen und entriegelt
      {% elif security_state == 'Closed & Locked' %}      
        Die Haustür ist geschlossen und verriegelt
      {% elif security_state == 'Open'%}      
        Die Haustür ist geöffnet
      {% else %}
        Die Haustür hat den unbekannten Status {{security_state}}
      {% endif %}  