# Wrapper sensor for sensor sr_waste_next of waste_collection_schedule
sensor:
  - name: sr_waste_next_ex
    unique_id: sr_waste_next_ex
    picture: /local/img/next.png
    icon: mdi:trash-can
    #unit_of_measurement: Tage
    state: > 
      {{ states('sensor.sr_waste_next') }}
    attributes:
      devices: >
        {{ states.sensor.sr_waste_next.attributes.values() | first |
        replace("blau", "Papierm체ll") | replace("gelb", "Wertstoff") |
        replace("grau", "Restm체ll") | replace("braun", "Biom체ll") | replace("Graue Tonne 14-t채glich,", "") }}
      date: >
        {% from 'get_waste_date.jinja' import get_waste_date %}        
        {{get_waste_date('grey')}}  
      days_to: > 
        {% set fullString = states('sensor.sr_waste_grey') %}
        {% set daysTo = fullString.split("|")[1] %}
        {{ daysTo  | int }}
      extended: >        
        {% set fullString =  states('sensor.sr_waste_grey') %}        
        {% set day = fullString.split("|")[3] %}        
        {% set locale = { 'Monday':'Montag', 'Tuesday':'Dienstag', 'Wednesday':'Mittwoch', 'Thursday':'Donnerstag', 'Friday':'Freitag', 'Saturday':'Samstag', 'Sunday':'Sonntag' } %}
        {{state_attr('sensor.sr_waste_next_ex', 'devices')}}
        {%- set daysTo = fullString.split("|")[1] | int -%}
        {% if daysTo == 0 %} heute{% elif daysTo == 1 %} morgen{% else %} am {{ locale.get(day) }} {% endif %}
#        {{','}} {{ state_attr('sensor.sr_waste_next_ex', 'date') }}
      