# Wrapper sensor for sensor sr_waste_brown of waste_collection_schedule
sensor:
  - name: sr_waste_brown_ex
    unique_id: sr_waste_brown_ex
    picture: /local/img/brown.png
    icon: mdi:leaf
    #unit_of_measurement: Tage
    state: > 
        {% from 'get_waste_state.jinja' import get_waste_state %}        
        {{get_waste_state('brown')}}  
    attributes:
      full: >
        {{ states('sensor.sr_waste_brown') }}      
      date: > 
        {% from 'get_waste_date.jinja' import get_waste_date %}        
        {{get_waste_date('brown')}}  
      day: > 
        {% from 'get_waste_day.jinja' import get_waste_day %}        
        {{get_waste_day('brown')}}     
      formatted: > 
        {% from 'get_waste_days_to_formatted.jinja' import get_waste_days_to_formatted %}        
        {{get_waste_days_to_formatted('brown')}}  
#        , {{ date }}
