sensor:
  - name: sr_wz_cover_window  
    state: >
      {% from 'get_covers_states.jinja' import get_covers_states %}
      {{get_covers_states('wohnzimmerfensterrolladen_tuya', 'state')}}                 
    attributes:
      is_open: >
        {% from 'get_covers_states.jinja' import get_covers_states %}    
        {{get_covers_states('wohnzimmerfensterrolladen_tuya', 'is_open')}}
      is_closed: >
        {% from 'get_covers_states.jinja' import get_covers_states %}    
        {{get_covers_states('wohnzimmerfensterrolladen_tuya', 'is_closed')}}
      get_position: >
        {% from 'get_covers_states.jinja' import get_covers_states %}    
        {{get_covers_states('wohnzimmerfensterrolladen_tuya', 'get_position')}}