sensor:
  - name: sr_sm_s916b_wrapper
    unique_id: sr_sm_s916b_wrapper
    state: >
      {% set locale = {'discharging':'Entlädt', 'charging':'Lädt'} %}
      {% set sm_s916b_battery_state = states('sensor.sm_s916b_battery_state') %}
      {{ locale.get(sm_s916b_battery_state)}}
    availability: >
      {{ has_value('sensor.sm_s916b_battery_state') }}
    icon: >
      {% if not states('sensor.sm_s916b_battery_state') is none %}
        {% if  states('sensor.sm_s916b_battery_state') == 'charging' %}  
            {{'mdi:battery-plus'}}
        {% else %}
          {{'mdi:battery-minus'}}
        {% endif %}
      {% else %}
        {{unknwon}}
      {% endif %}