sensor:
  - name: sr_gz_cover
    state: >
      {% if states('cover.gastezimmerfensterrolladen_tuya') == 'closed' %}
        open
      {% else %}
        closed
      {% endif %}      
    attributes:
      is_open: >    
        {% if not state_attr('cover.gastezimmerfensterrolladen_tuya', 'current_position') is none %}                    
          {{ state_attr('cover.gastezimmerfensterrolladen_tuya', 'current_position') | int  == 0}}            
        {% endif %}         
      is_closed: >
        {% if not state_attr('cover.gastezimmerfensterrolladen_tuya', 'current_position') is none %}                          
          {{ state_attr('cover.gastezimmerfensterrolladen_tuya', 'current_position') | int  == 100}}                  
        {% endif %}          
      get_position: >
        {% if not state_attr('cover.gastezimmerfensterrolladen_tuya', 'current_position') is none %}            
          {{ state_attr('cover.gastezimmerfensterrolladen_tuya', 'current_position')}}                  
        {% endif %}          