sensor:

  - name: sr_fl_nuki_frontdoor_security_state_icon
    unique_id: sr_fl_nuki_frontdoor_security_state_icon
    state: >
      {% set security_states = states('sensor.sr_fl_nuki_frontdoor_info_security_state') %}
      {% if security_states == 'Geschlossen und entriegelt' %}
        mdi:door-closed
      {% elif security_states == 'Geschlossen und verriegelt' %}  
        mdi:door-closed-lock
      {% else %} 
        mdi:door-open
      {% endif %}

  - name: sr_fl_nuki_frontdoor_info_security_state
    unique_id: sr_fl_nuki_frontdoor_info_security_state
    state: >
      {% set locking_state = states('lock.haustur') %}
      {% set opening_state = states('binary_sensor.haustur_door_sensor') %}
      {% set locking_states = {
        "unlocked": "entriegelt",
        "locked": "verriegelt",
        "unavailable": "Nicht verfügbar",
        "unknown": "Nicht bekannt"}
      %}
      {% set opening_states = {
        "off": "Geschlossen",
        "on": "Geöffnet ", 
        "unavailable": "Nicht verfügbar",
        "unknown": "Nicht bekannt"}
      %}
      Die Haustür ist {{opening_states[opening_state]}} und {{locking_states[locking_state]}}
    icon: "{{states('sensor.sr_fl_nuki_frontdoor_security_state_icon')}}"
    
  - name: sr_fl_nuki_frontdoor_security_state
    unique_id: sr_fl_nuki_frontdoor_security_state
    state: >
      {% set opening_state = states('binary_sensor.haustur_door_sensor') %}
      {% set opening_states = {
        "off": "closed",
        "on": "open ", 
        "unavailable": "unavailable",
        "unknown": "unknown"}
      %}
      {{opening_states[opening_state]}}
    icon: "{{states('sensor.sr_fl_nuki_frontdoor_security_state_icon')}}"