#Welche Lampen sind eingeschaltet
sensor:
  - name: sr_ha_lamps_on_count
    unique_id: sr_ha_lamps_on_count
    state: >
      {% set filter = states('input_text.it_ha_lamps_on_filter') %}
      {% set minutes = timedelta(minutes=states('input_number.in_ha_lamps_on_alarm_period') | int) %}
      {% set entity_name = "light.ha_grp_lampen" %}
      {% set type = "light." %}

      {% set result = namespace(entity_ids=[]) %}
      {% set entity_list = filter.split(',') %}
      {% for entity_id in entity_list %}
          {% set result.entity_ids = result.entity_ids  + [type + entity_id] %}
      {% endfor %}
      {% set filter = result.entity_ids %}

      {% set  switches =  expand(states.switch) | selectattr('state', 'eq', 'on') |
          selectattr('entity_id','in', expand(entity_name)) |
          expand(entity_name) | selectattr('state', 'eq', 'on') | 
          selectattr('last_changed', '<', (now() - minutes)) | list%}
      {% set switches =  switches | rejectattr('entity_id', 'in', filter) | map(attribute='name') | list %}

      {{ switches | count }}
