#Welche Schalter sind eingeschaltet
sensor:
  - name: sr_ha_switches_on
    unique_id: sr_ha_switches_on
    state: >
      {% from 'get_LightsOrLampsOrSwichtes_on.jinja' import get_LightsOrLampsOrSwichtes_on %}        
      {{get_LightsOrLampsOrSwichtes_on('count',false, 'switches')}}
    attributes:
      switches_on: >
        {% from 'get_LightsOrLampsOrSwichtes_on.jinja' import get_LightsOrLampsOrSwichtes_on %}        
        {{get_LightsOrLampsOrSwichtes_on('',false, 'switches')}}
