sensor:
  - name: sr_ha_motion_detectors_info
    unique_id: sr_ha_motion_detectors_info
    icon: mdi:motion-sensor
    availability: >
      {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
      {{ not get_motion_detctors_info_for_area('kuche','') is none
        and not get_motion_detctors_info_for_area('gastetoilette','') is none
        and not get_motion_detctors_info_for_area('badezimmer','') is none
        and not get_motion_detctors_info_for_area('flur','') is none
        and not get_motion_detctors_info_for_area('schlafzimmer','') is none
        and not get_motion_detctors_info_for_area('dachgeschoss','') is none
        and not get_motion_detctors_info_for_area('treppenhaus','') is none
        and not get_motion_detctors_info_for_area('ankleidezimmer','') is none        
        and not get_motion_detctors_info_for_area('wohnzimmer','') is none
      }}
    state: >
      {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
      {{get_motion_detctors_info_for_area('','count')}}
    attributes:
      motion_detectors_info_ku: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('kuche','')}}
      motion_detectors_info_gt: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('gastetoilette','')}}
      motion_detectors_info_of: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('obergeschossflur','')}}        
      motion_detectors_info_bz: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('badezimmer','')}}
      motion_detectors_info_gz: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('gastezimmer','')}}        
      motion_detectors_info_sz: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('schlafzimmer','')}}
      motion_detectors_info_az: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('ankleidezimmer','')}}
      motion_detectors_info_fl: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('flur','')}}
      motion_detectors_info_dg: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('dachgeschoss','')}}
      motion_detectors_info_tr: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('treppenhaus','')}}
      motion_detectors_info_wz: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('wohnzimmer','')}}        
      motion_detectors_info_all: >
        {% set list = namespace(sensors=[]) %}
        {% if (state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_ku') != None and
          state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_gt') != None  and
          state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_bz') != None and  
          state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_sz') != None and
          state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_az') != None and
          state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_fl') != None and  
          state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_dg') != None and  
          state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_tr') != None and
          state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_wz') != None)          
        %}          
          {% set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_ku')%}
          {%set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_gt')%}
          {%set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_bz')%}
          {%set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_sz')%}
          {%set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_fl')%}
          {%set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_dg')%}
          {%set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_tr')%}
          {%set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_az')%} 
          {%set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_wz')%}          
          {{list.sensors}}
        {% else %}           
          unkown
        {% endif %}
