sensor:
  - name: sr_ha_electricity_contract_live_time
    state: >
      {% set end = as_timestamp(states('input_datetime.idt_ha_electricity_contract_ends')) %}
      {% set now = as_timestamp(now()) %}
      {% set time = end - now | int(0) %}
      {% set days = (time/86400) | int %}         
      {% set hours = (time / 3600 % 24) | int %}
      {% set minutes = (((time / 3600) % 1) * 60) | int %}
      {% set month = days / 365 * 12   %}
      {{ days ~ 'd:' ~ hours ~ 'h:' ~ minutes ~ 'm' }}
    attributes:
      month: >
        {% set end = as_timestamp(states('input_datetime.idt_ha_electricity_contract_ends')) %}
        {% set now = as_timestamp(now()) %}
        {% set time = end - now | int(0) %}
        {% set days = (time/86400) | int %}         
        {% set hours = (time / 3600 % 24) | int %}
        {% set minutes = (((time / 3600) % 1) * 60) | int %}
        {% set month = days / 365 * 12   %}
        {{ month | round(1)}}