#Welche Lichtschalter sind eingeschaltet
sensor:
  - name: sr_ha_light_switches_on
    unique_id: sr_ha_light_switches_on
    state: >
      {% from 'get_LightsOrLampsOrSwichtes_on.jinja' import get_LightsOrLampsOrSwichtes_on %}        
      {{get_LightsOrLampsOrSwichtes_on('count',false, 'lights')}}
    attributes:
      light_switches_on: >
        {% from 'get_LightsOrLampsOrSwichtes_on.jinja' import get_LightsOrLampsOrSwichtes_on %}        
        {{get_LightsOrLampsOrSwichtes_on('',false, 'lights')}}
