sensor:
  - name: sr_ha_motion_detectors_info
    unique_id: sr_ha_motion_detectors_info
    icon: mdi:motion-sensor
    availability: >
      {{ not state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_ku') is none
        and not state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_gt') is none
        and not state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_bz') is none
        and not state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_sz') is none
        and not state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_fl') is none
        and not state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_dg') is none
        and not state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_tr') is none
      }}
    state: >
      {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
      {{get_motion_detctors_info_for_area('','count')}}      
    attributes:
      motion_detectors_info_ku: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('kuche','')}}         
      motion_detectors_info_gt: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('gastetoilette','')}}         
      motion_detectors_info_bz: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('badezimmer','')}}      
      motion_detectors_info_sz: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('schlafzimmer','')}}      
      motion_detectors_info_fl: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('flur','')}}         
      motion_detectors_info_dg: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('dachgeschoss','')}}      
      motion_detectors_info_tr: >
        {% from 'get_motion_detctors_info_for_area.jinja' import get_motion_detctors_info_for_area %}        
        {{get_motion_detctors_info_for_area('treppenhaus','')}}         
      motion_detectors_info_all: >  
        {% set list = namespace(sensors=[]) %}
        {% set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_ku')%}
        {%set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_gt')%}
        {%set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_bz')%}
        {%set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_sz')%}
        {%set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_fl')%}
        {%set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_dg')%}
        {%set list.sensors = list.sensors + state_attr('sensor.sr_ha_motion_detectors_info', 'motion_detectors_info_tr')%} 
        {{list.sensors}}