sensor:
  - name: sr_ha_pending_notifications_list
    unique_id: sr_ha_pending_notifications_list
    icon: mdi:information
    # for pretty output, the code must be so formatted
    state: >
      {% set output = namespace(out= "") %}
      {% set notifications = state_attr("sensor.sr_ha_pending_notification", "list") | default([], true) %}      
      {% if notifications | length > 0 %}      
      {% for i in range(notifications | length) %}
      {% set counter = i+1 %}
      {% set output.out = output.out + counter|string +  ". " + notifications[i]['message'] + "\n" %}
      {% endfor %}
      {% endif %}
      {{output.out}}
