#Welche Lampen sind eingeschaltet
sensor:
  - name: sr_ha_lamps_on
    unique_id: sr_ha_lamps_on
    state: >
      {{expand('light.ha_grp_lampen') | count}}
    attributes:
      lamps_on: >
        {% set toExclucde = namespace(entities=['light.first_led_hardware_instance', 'light.first_led_hardware_instance_2']) %}
        {%-  for state in expand(states.light)
          if state.state == "on" and
          not state.entity_id in toExclucde.entities
          and state.entity_id in expand('light.ha_grp_lampen') | map(attribute='entity_id') | list 
        -%}
        {%- if loop.first %}
          Die Lampe {% elif loop.last %} und die Lampe {% else %}, die Lampe {% endif -%}    
          {{ state.name -}} {% if loop.last %} ist eingeschaltet. {% endif -%}      
        {% else %}
          Es sind keine Lampen eingeschaltet.
        {% endfor %}        

#        {% set switches =  expand(states.light) | selectattr('state', 'eq', 'on') |
#        selectattr('entity_id', 'in', expand('light.ha_grp_lampen')) |
#        expand('light.ha_grp_lampen') | selectattr('state', 'eq', 'on') | list %}        
#        {%- set filter = ['light.first_led_hardware_instance', 'light.first_led_hardware_instance_2'] -%}
#        {%- set switches =  switches | rejectattr('entity_id', 'in', filter) | map(attribute='name') | list -%}                
#        {% if (switches | length) == 0 %}
#          Es sind keine Lampen eingeschaltet.
#        {% elif (switches | length) == 1 %}
#          Die Lampe {{switches[0]}} ist eingeschlatet. 
#        {%- else  -%}
#          Die Lampen {{""}}
#          {%- for i in range(switches|length) -%}
#            {%- if i == (switches|length)-1 -%}
#              {{" "}}und {{switches[i]}} sind eingeschlatet.
#            {%- else -%}
#              {{switches[i]}} 
#              {%- if (i + 2) in range(switches|length) -%}
#                {{", "}}
#              {%- endif %}  
#            {%- endif -%}    
#          {% endfor %}
#        {% endif %}          