sensor:
  - name: sr_ha_pending_notifications_info
    unique_id: sr_ha_pending_notifications_info
    icon: mdi:information
    # for pretty output, the code must be so formatted
    state: >
      {{ state_attr("sensor.sr_ha_pending_notification", "list") | default([], true) | count }}
    attributes:
      list: >
        {% set output = namespace(out= "") %}
        {% set notifications = state_attr("sensor.sr_ha_pending_notification", "list") | default([], true) %}      
        {% if notifications | length > 0 %}      
        {% for i in range(notifications | length) %}
        {% set counter = i+1 %}
        {% set text = notifications[i]['message'].replace("\n", "") %}
        {% set timestamp = notifications[i]['timestamp'] %}
        {% set output.out = output.out + counter|string +  ". " + as_timestamp(timestamp) | timestamp_custom('%d.%m.%Y %H:%M') + "\n" +  text + "\n" %}
        {% endfor %}
        {% endif %}
        {{output.out}}
