#Welche Lampen sind eingeschaltet
sensor:
  - name: sr_ha_lamps_on
    unique_id: sr_ha_lamps_on
    state: >
      {% from 'get_LightsOrLampsOrSwichtes_on.jinja' import get_LightsOrLampsOrSwichtes_on %}        
      {{get_LightsOrLampsOrSwichtes_on('count',false, 'lamps')}}
    attributes:
      lamps_on: >
        {% from 'get_LightsOrLampsOrSwichtes_on.jinja' import get_LightsOrLampsOrSwichtes_on %}        
        {{get_LightsOrLampsOrSwichtes_on('',false, 'lamps')}}
