sensor:
  - name: sr_ku_cover
    state: >
      {% if states('cover.kuchenfenster_curtain') == 'closed' %}
        opened
      {% else %}
        closed
      {% endif %}      
    attributes:
      is_open: >    
        {{ state_attr('cover.kuchenfenster_curtain', 'current_position') | int  == 0}}            
      is_closed: >
        {{ state_attr('cover.kuchenfenster_curtain', 'current_position') | int  == 100}}                  
      get_position: >
        {{ state_attr('cover.kuchenfenster_curtain', 'current_position')}}                  