binary_sensor:
  - name: bs_lawn_sprinkler
    availability: >
      {{ not states('sensor.gw1100a_v2_2_3_solar_lux') is none and
        not states('input_number.in_gr_lawn_sprinkler_lux_treshhold') is none and
        not states('sensor.gw1100a_v2_2_3_daily_rain_rate') is none
      }}  
    state: >
      {% set state_sensor = states('sensor.gw1100a_v2_2_3_solar_lux') %}
      {% set state_threshold = states('input_number.in_gr_lawn_sprinkler_lux_treshhold') %}
      {{ (states('sensor.gw1100a_v2_2_3_rain_rate') | float == 0)
        and (states('sensor.gw1100a_v2_2_3_daily_rain_rate') | float <= states('input_number.in_gr_daily_rain_rate_treshhold') | float)
        and (is_number(state_sensor) and is_number(state_threshold) and (state_sensor | float >= state_threshold | float))
        and (now().month | string in states('input_text.it_ha_lawn_sprinkler_summer_months'))
      }}
#    - condition: template
#      value_template: "{{ states('sensor.sr_gr_average_statistic_temperature') | float >= states('input_number.in_gr_lawn_sprinkler_temperature_treshhold') | float }}"      