sensor:
  - name: sr_wz_cover_door
    state: >
      {% if states('cover.wohnzimmertur_curtain') == 'closed' %}
        opened
      {% else %}
        closed
      {% endif %}      
    attributes:
      is_open: >    
        {{ state_attr('cover.wohnzimmertur_curtain', 'current_position') | int  == 0}}            
      is_closed: >
        {{ state_attr('cover.wohnzimmertur_curtain', 'current_position') | int  == 100}}                  
      get_position: >
        {{ state_attr('cover.wohnzimmertur_curtain', 'current_position')}}                  