sensor:
  - name: sr_wz_cover_door
    state: >
      {% if states('cover.wohnzimmertur_curtain') == 'closed' %}
        open
      {% else %}
        closed
      {% endif %}      
    attributes:
      is_open: >    
        {% if not state_attr('cover.wohnzimmertur_curtain', 'current_position') is none %}      
          {{ state_attr('cover.wohnzimmertur_curtain', 'current_position') | int  == 0}}            
        {% endif %}
      is_closed: >
        {% if not state_attr('cover.wohnzimmertur_curtain', 'current_position') is none %}            
          {{ state_attr('cover.wohnzimmertur_curtain', 'current_position') | int  == 100}}                  
        {% endif %}
      get_position: >
        {% if not state_attr('cover.wohnzimmertur_curtain', 'current_position') is none %}      
          {{ state_attr('cover.wohnzimmertur_curtain', 'current_position')}}                  
        {% endif %}