#Welche Rolladen sind geöffnet
#Welche Rolladen sind offen
sensor:
  - name: sr_ha_covers_tuya_open
    state: >    
      {{expand('group.ha_grp_covers_tuya') | count - 1}}
# Subtract the cover.leinwand
    attributes:
      covers_open: >
        {% set covers =  expand('group.ha_grp_covers_tuya') | selectattr('state', 'eq', 'open') %}
        {% set filter = ['cover.leinwand'] %}
        {% set covers =  covers | rejectattr('entity_id', 'in', filter) | map(attribute='name') | list %}        
        {% if (covers | length) == 0 %}
          Es sind keine Rolladen geöffnet.
        {% elif (covers | length) == 1 %}
          Der Rolladen {{covers[0]}} ist geöffnet. 
        {%- else  -%}
          Die Rolladen von {{""}}
          {%- for i in range(covers|length) -%}
            {%- if i == (covers|length)-1 -%}
              {{" "}}und {{covers[i].split("rolladen")[0]}} sind geöffnet.
            {%- else -%}
              {{covers[i].split("rolladen")[0]}}
              {%- if (i + 2) in range(covers|length) -%}
                {{", "}}
              {%- endif %}                
            {%- endif -%}    
          {% endfor %}
        {% endif %}      
#    {% set toExclucde = namespace(entities=['cover.leinwand']) %}
#    {%-  for state in states.cover
#      if state.state == "open" and
#      not state.entity_id in toExclucde.entities
#      and state.entity_id in expand('group.ha_grp_rolladen') | map(attribute='entity_id') | list 
#    -%}
#    {%- if loop.first %}
#      Der Rolladen von {% elif loop.last %} und der Rolladen von {% else %}, der Rolladen von {% endif -%}    
#      {{ state.name.split("rolladen")[0] }} {%- if loop.last %} ist geöffnet. {% endif -%}      
#    {% else %}
#      Es sind keine Rolladen geöffnet.
#    {% endfor %}   
            