substitutions:
  name: everything-presence-one-7f6cbc
packages:
  Everything_Smart_Technology.Everything_Presence_One: github://everythingsmarthome/presence-one/everything-presence-one.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: !secret api_encryption_key


wifi:
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password
